inputs:
  python-version:
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
    name: Checkout
  - name: Echo if not sportwig
    if: ${{ github.repository != 'swholdings/sportwig' }}
    run: echo "Not Sportwig"
    shell: bash