inputs:
  python-version:
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
    name: Checkout
  - uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}
  - name: Install Python dependencies
    run: |
      python -m pip install pip -U
      python -m pip install -r requirements/deploy.txt
    shell: bash
  - name: Echo if not sportwig
    if: ${{ github.repository != 'swholdings/sportwig' }}
    run: echo "Not Sportwig"
    shell: bash